name: GoReleaser on Release Commit

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: contains(github.event.head_commit.message, 'release')
    runs-on: my-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23 
      - name: Import GPG private key
        run: echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v2.7.0
          install-only: true
      - name: Check GoReleaser version
        run: goreleaser --version

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }} # nếu bạn dùng ký số
        run: goreleaser release --clean --config .goreleaser.yml
